three:
  - ucsd49
  - ucsd51

dead:
  - duke-merge
  - duke17
  - duke29
  - duke33
  - duke39
  - duke40
  - duke6
  - duke8
  - ohsu-merge
  - ohsu10
  - ohsu32
  - ohsu44
  - ohsu45
  - ohsu46 
  - ohsu9
  - sri-merge
  - sri17
  - sri29
  - sri33
  - sri38
  - sri39
  - sri40
  - sri5
  - sri6
  - ucsd-merge
  - ucsd11
  - ucsd12
  - ucsd23
  - ucsd34
  - ucsd41
  - ucsd42
  - ucsd43
  - ucsd45
  - ucsd46
  - ucsd47
  - ucsd48
  - ucsd56
  - ucsd60
  - ucsd61
  - ucsd98
  - ucsd99
  - upmc-merge
  - upmc27
  - upmc28
  - upmc3
  - upmc37
  - upmc4
  - admin1
  - admin2
  - admin35
  - admin36
  - admin50